// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// option_price_call_black_scholes
double option_price_call_black_scholes(const double& S, const double& K, const double& r, const double& sigma, const double& time);
RcppExport SEXP _StatComp22095_option_price_call_black_scholes(SEXP SSEXP, SEXP KSEXP, SEXP rSEXP, SEXP sigmaSEXP, SEXP timeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double& >::type S(SSEXP);
    Rcpp::traits::input_parameter< const double& >::type K(KSEXP);
    Rcpp::traits::input_parameter< const double& >::type r(rSEXP);
    Rcpp::traits::input_parameter< const double& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const double& >::type time(timeSEXP);
    rcpp_result_gen = Rcpp::wrap(option_price_call_black_scholes(S, K, r, sigma, time));
    return rcpp_result_gen;
END_RCPP
}
// option_price_put_black_scholes
double option_price_put_black_scholes(const double& S, const double& K, const double& r, const double& sigma, const double& time);
RcppExport SEXP _StatComp22095_option_price_put_black_scholes(SEXP SSEXP, SEXP KSEXP, SEXP rSEXP, SEXP sigmaSEXP, SEXP timeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double& >::type S(SSEXP);
    Rcpp::traits::input_parameter< const double& >::type K(KSEXP);
    Rcpp::traits::input_parameter< const double& >::type r(rSEXP);
    Rcpp::traits::input_parameter< const double& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const double& >::type time(timeSEXP);
    rcpp_result_gen = Rcpp::wrap(option_price_put_black_scholes(S, K, r, sigma, time));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_StatComp22095_option_price_call_black_scholes", (DL_FUNC) &_StatComp22095_option_price_call_black_scholes, 5},
    {"_StatComp22095_option_price_put_black_scholes", (DL_FUNC) &_StatComp22095_option_price_put_black_scholes, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_StatComp22095(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
