# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title B-S Option Pricing Model
#' @description use B-S option pricing model to compute the price of European call option
#' @param S underlying asset price
#' @param K exercise price
#' @param r risk free interest rate
#' @param sigma volatility of assets(year)
#' @param time term of contract
#' @return the price of one European call option
#' @examples
#' \dontrun{
#' option_price_call_black_scholes(4.019, 3.3, 0.022685, 0.4199, 0.05479)
#' }
#' @export
option_price_call_black_scholes <- function(S, K, r, sigma, time) {
    .Call('_StatComp22095_option_price_call_black_scholes', PACKAGE = 'StatComp22095', S, K, r, sigma, time)
}

#' @title B-S Option Pricing Model
#' @description use B-S option pricing model to compute the price of European put option
#' @param S underlying asset price
#' @param K exercise price
#' @param r risk free interest rate
#' @param sigma volatility of assets(year)
#' @param time term of contract
#' @return the price of one European put option
#' @examples
#' \dontrun{
#' option_price_put_black_scholes(4.019, 4.0, 0.022685, 0.1717, 0.05479)
#' }
#' @export
option_price_put_black_scholes <- function(S, K, r, sigma, time) {
    .Call('_StatComp22095_option_price_put_black_scholes', PACKAGE = 'StatComp22095', S, K, r, sigma, time)
}

